services:
  rest-service:
    build:
      context: ./rest-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - SWAGGER_URL=http://localhost:5000

  graphql-service:
    build:
      context: ./graphql-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - SWAGGER_URL=http://localhost:3000

  soap-service:
    build:
      context: ./soap-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - rest-service
      - graphql-service
      - soap-service

networks:
  app-network:
    driver: bridge
